project_id = "yvhrzqrdzykbvhifsoxk"

[functions.analyze-project]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.parse-exam-pdf]
verify_jwt = false

[functions.recommend-courses]
verify_jwt = false