
-- Delete all existing courses and re-insert with real URLs
DELETE FROM public.explorer_course_progress;
DELETE FROM public.academy_courses;

-- PATH 1: AI Foundations (77d2abb2-a86d-40ec-bede-1b13c658dec9)
INSERT INTO public.academy_courses (path_id, title, title_es, description, description_es, platform, external_url, duration_minutes, skill_level, language, skills_learned, category, tool, sort_order) VALUES
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Introduction to Generative AI', 'Introducción a la IA Generativa', 'Understand what generative AI is, how it works, and its applications.', 'Comprende qué es la IA generativa, cómo funciona y sus aplicaciones.', 'Google Cloud', 'https://www.cloudskillsboost.google/paths/118', 45, 'beginner', 'en', ARRAY['AI Basics','Generative AI','Prompt Refinement'], 'ai-foundations', 'Google AI', 1),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'AI for Everyone', 'IA Para Todos', 'Identify AI opportunities in business and basic project planning.', 'Identifica oportunidades de IA en negocios y planificación básica de proyectos.', 'Coursera', 'https://www.coursera.org/learn/ai-for-everyone', 360, 'beginner', 'en', ARRAY['AI Strategy','Business AI','Project Planning'], 'ai-foundations', 'General AI', 2),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Google AI Essentials', 'Esenciales de Google AI', 'Apply AI to workflows, use tools for research and brainstorming.', 'Aplica IA a flujos de trabajo, usa herramientas para investigación y lluvia de ideas.', 'Coursera', 'https://www.coursera.org/learn/google-ai-essentials', 600, 'beginner', 'en', ARRAY['AI Workflows','Research','Brainstorming'], 'ai-foundations', 'Google AI', 3),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Elements of AI', 'Elementos de IA', 'AI ethics, basic ML applications, and responsible AI use.', 'Ética de IA, aplicaciones básicas de ML y uso responsable de IA.', 'University of Helsinki', 'https://www.elementsofai.com/', 1800, 'beginner', 'en', ARRAY['AI Ethics','Machine Learning','Responsible AI'], 'ai-foundations', 'General AI', 4),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'AI Fluency: Framework and Foundations', 'Fluidez en IA: Marco y Fundamentos', 'Using Claude for tasks, context management, and AI assistants.', 'Uso de Claude para tareas, gestión de contexto y asistentes de IA.', 'Anthropic', 'https://www.anthropic.com/learn/claude-for-you', 180, 'beginner', 'en', ARRAY['Claude','AI Assistants','Context Management'], 'ai-foundations', 'Claude', 5),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Foundations of Prompt Engineering', 'Fundamentos de Ingeniería de Prompts', 'Design effective prompts using chain-of-thought and optimization techniques.', 'Diseña prompts efectivos usando cadena de pensamiento y técnicas de optimización.', 'AWS Skill Builder', 'https://explore.skillbuilder.aws/learn/courses/17763/foundations-of-prompt-engineering', 240, 'beginner', 'en', ARRAY['Prompt Design','Chain-of-Thought','Output Optimization'], 'ai-foundations', 'AWS AI', 6),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'ChatGPT Prompt Engineering for Developers', 'Ingeniería de Prompts con ChatGPT para Desarrolladores', 'Build apps with prompts, iterate inputs, and integrate with APIs.', 'Construye apps con prompts, itera entradas e integra con APIs.', 'DeepLearning.AI', 'https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/', 60, 'beginner', 'en', ARRAY['Prompt Engineering','API Integration','Prototyping'], 'ai-foundations', 'ChatGPT', 7),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Prompt Engineering Full Course 2026', 'Curso Completo de Prompt Engineering 2026', 'Advanced prompting for content, data analysis, and automation.', 'Prompting avanzado para contenido, análisis de datos y automatización.', 'YouTube (Simplilearn)', 'https://www.youtube.com/watch?v=I1MEiaG0vW4', 120, 'beginner', 'en', ARRAY['Advanced Prompting','Data Analysis','Content Creation'], 'ai-foundations', 'ChatGPT', 8),

-- PATH 2: AI Automation (2fffe876-36e6-47db-b44c-114ec405fc8f)
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Generative AI for Beginners', 'IA Generativa para Principiantes', 'Build simple AI models and use LLMs for automation.', 'Construye modelos de IA simples y usa LLMs para automatización.', 'Microsoft Learn', 'https://learn.microsoft.com/en-us/training/paths/introduction-generative-ai/', 540, 'beginner', 'en', ARRAY['LLMs','AI Models','Task Automation'], 'automation', 'Microsoft AI', 1),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'No-Code ML and Generative AI on AWS', 'ML Sin Código e IA Generativa en AWS', 'Build ML models without code and integrate generative AI.', 'Construye modelos ML sin código e integra IA generativa.', 'AWS Skill Builder', 'https://skillbuilder.aws/learn/2K7VKSFTEN/nocode-machine-learning-and-generative-ai-on-aws-includes-labs/G3HQ6CQAEX', 240, 'beginner', 'en', ARRAY['No-Code','ML Models','AWS AI'], 'automation', 'AWS', 2),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Generative AI Full Course 2026', 'Curso Completo de IA Generativa 2026', 'LangChain for workflows, RAG implementation, end-to-end pipelines.', 'LangChain para flujos de trabajo, implementación RAG, pipelines de extremo a extremo.', 'YouTube (Simplilearn)', 'https://www.youtube.com/watch?v=mnkiYN6qikw', 240, 'beginner', 'en', ARRAY['LangChain','RAG','Automation Pipelines'], 'automation', 'LangChain', 3),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Generative AI Mastery', 'Dominio de IA Generativa', 'Prompt chaining, building AI workflows, 900+ curated resources.', 'Encadenamiento de prompts, flujos de trabajo con IA, 900+ recursos curados.', 'Class Central', 'https://www.classcentral.com/report/generative-ai-online-courses', 480, 'intermediate', 'en', ARRAY['Prompt Chaining','AI Workflows','App Building'], 'automation', 'Multiple', 4),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Supercharge Productivity: ChatGPT & Prompt Engineering', 'Supercarga tu Productividad: ChatGPT y Prompt Engineering', 'AI for scheduling, content, and collaboration workflows.', 'IA para programación, contenido y flujos de colaboración.', 'Class Central', 'https://www.classcentral.com/course/supercharge-productivity-chatgpt-prompt-engineering-205485', 120, 'beginner', 'en', ARRAY['Productivity','Scheduling','Collaboration'], 'automation', 'ChatGPT', 5),

-- PATH 3: Claude Code & AI Development (25ec054d-d234-4ed3-98d9-812305542e7d)
('25ec054d-d234-4ed3-98d9-812305542e7d', 'Claude Code in Action', 'Claude Code en Acción', 'Using Claude for code generation, debugging, and workflow automation.', 'Uso de Claude para generación de código, depuración y automatización de flujos.', 'Anthropic', 'https://anthropic.skilljar.com/claude-code-in-action', 120, 'intermediate', 'en', ARRAY['Claude Code','Debugging','Workflow Automation'], 'development', 'Claude', 1),
('25ec054d-d234-4ed3-98d9-812305542e7d', 'AI Python for Beginners', 'Python con IA para Principiantes', 'Write, debug, and test Python code with AI assistance.', 'Escribe, depura y prueba código Python con asistencia de IA.', 'DeepLearning.AI', 'https://www.deeplearning.ai/short-courses/ai-python-for-beginners/', 600, 'beginner', 'en', ARRAY['Python','AI Coding','App Building'], 'development', 'Python', 2),
('25ec054d-d234-4ed3-98d9-812305542e7d', 'AI-For-Beginners (Microsoft)', 'IA Para Principiantes (Microsoft)', 'Building neural networks, labs with TensorFlow/PyTorch.', 'Construcción de redes neuronales, laboratorios con TensorFlow/PyTorch.', 'GitHub (Microsoft)', 'https://github.com/microsoft/AI-For-Beginners', 5040, 'beginner', 'en', ARRAY['Neural Networks','TensorFlow','PyTorch'], 'development', 'TensorFlow', 3),
('25ec054d-d234-4ed3-98d9-812305542e7d', 'Fundamentals of Deep Learning', 'Fundamentos de Deep Learning', 'Training models for image recognition and deployment.', 'Entrenamiento de modelos para reconocimiento de imágenes y despliegue.', 'NVIDIA DLI', 'https://www.nvidia.com/en-us/training/online/', 480, 'beginner', 'en', ARRAY['Deep Learning','Image Recognition','Model Deployment'], 'development', 'NVIDIA', 4),
('25ec054d-d234-4ed3-98d9-812305542e7d', 'AI Agents Course', 'Curso de Agentes de IA', 'Building multi-agent systems and tool integration.', 'Construcción de sistemas multi-agente e integración de herramientas.', 'Hugging Face', 'https://huggingface.co/learn/agents-course/en/unit0/introduction', 480, 'intermediate', 'en', ARRAY['AI Agents','Multi-Agent Systems','Tool Integration'], 'development', 'Hugging Face', 5),
('25ec054d-d234-4ed3-98d9-812305542e7d', 'Learn to Build AI Agents', 'Aprende a Construir Agentes de IA', 'Prompt design for agents, multimodal integration, agentic workflows.', 'Diseño de prompts para agentes, integración multimodal, flujos agénticos.', 'Plain English', 'https://ai.plainenglish.io/learn-to-build-ai-agents-9-free-courses-you-cant-miss-in-2026-2caee0e71369', 180, 'beginner', 'en', ARRAY['Agent Design','Multimodal AI','Agentic Workflows'], 'development', 'Multiple', 6),

-- PATH 4: AI for Creative Work (8a9c4660-393e-4a4c-ac4e-b6ea62660d96)
('8a9c4660-393e-4a4c-ac4e-b6ea62660d96', 'DALL-E for AI Image Generation', 'DALL-E para Generación de Imágenes con IA', 'Text-to-image prompts, editing with inpainting techniques.', 'Prompts de texto a imagen, edición con técnicas de inpainting.', 'MyGreatLearning', 'https://www.mygreatlearning.com/academy/learn-for-free/courses/dall-e-for-ai-image-generation', 90, 'beginner', 'en', ARRAY['DALL-E','Image Generation','Inpainting'], 'creative', 'DALL-E', 1),
('8a9c4660-393e-4a4c-ac4e-b6ea62660d96', 'Midjourney, DALL-E, Stable Diffusion: AI Art Masterclass', 'Midjourney, DALL-E, Stable Diffusion: Masterclass de Arte IA', 'Generating and refining AI art with multiple tools.', 'Generación y refinamiento de arte con IA usando múltiples herramientas.', 'Udemy', 'https://www.udemy.com/course/midjourney-dall-e-stable-diffusion-ai-art-masterclass/', 300, 'beginner', 'en', ARRAY['Midjourney','Stable Diffusion','AI Art'], 'creative', 'Midjourney', 2),
('8a9c4660-393e-4a4c-ac4e-b6ea62660d96', 'Image Generation with AI', 'Generación de Imágenes con IA', 'Stable Diffusion for images, denoising, advanced generation.', 'Stable Diffusion para imágenes, eliminación de ruido, generación avanzada.', 'Coursera', 'https://www.coursera.org/learn/image-generation-with-ai-training-course', 180, 'intermediate', 'en', ARRAY['Stable Diffusion','Denoising','Advanced Generation'], 'creative', 'Stable Diffusion', 3),

-- PATH 5: AI for Business Execution (cc31efb3-8329-477e-8e19-8b96ae1e5126)
('cc31efb3-8329-477e-8e19-8b96ae1e5126', 'Mastering AI Agents for Business', 'Dominando Agentes de IA para Negocios', 'LangChain, AutoGen for multi-agent systems in business operations.', 'LangChain, AutoGen para sistemas multi-agente en operaciones de negocio.', 'Medium/Hugging Face', 'https://medium.com/@maximilian.vogel/mastering-ai-agents-the-10-best-free-courses-tutorials-learning-tools-46bc380a19d1', 480, 'intermediate', 'en', ARRAY['LangChain','AutoGen','Business Automation'], 'business', 'LangChain', 1),

-- SPANISH COURSES - distributed across paths
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Elementos de IA', 'Elementos de IA', 'AI basics, ethics, simple applications in daily work.', 'Fundamentos de IA, ética y aplicaciones simples en el trabajo diario.', 'University of Helsinki', 'https://www.elementsofai.com/es', 1800, 'beginner', 'es', ARRAY['Fundamentos IA','Ética IA','Aplicaciones Prácticas'], 'ai-foundations', 'General AI', 9),
('cc31efb3-8329-477e-8e19-8b96ae1e5126', 'IA Para Todos (Español)', 'IA Para Todos', 'Identifying AI use cases in business and freelance projects.', 'Identificar casos de uso de IA en negocios y proyectos freelance.', 'Coursera', 'https://www.coursera.org/learn/ai-for-everyone-es', 600, 'beginner', 'es', ARRAY['Estrategia IA','Negocios','Marketing con IA'], 'business', 'General AI', 2),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Fundamentos de IA Generativa', 'Fundamentos de IA Generativa', 'Using LLMs for content and automation with Microsoft tools.', 'Uso de LLMs para contenido y automatización con herramientas de Microsoft.', 'Microsoft Learn', 'https://learn.microsoft.com/es-es/training/paths/introduction-generative-ai/', 360, 'beginner', 'es', ARRAY['LLMs','Automatización','Microsoft Copilot'], 'automation', 'Microsoft AI', 6),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Curso de Prompt Engineering en Español', 'Curso de Prompt Engineering', 'Advanced prompting: chain-of-thought, role-playing for better outputs.', 'Prompting avanzado: cadena de pensamiento, role-playing para mejores resultados.', 'YouTube (EDteam)', 'https://www.youtube.com/watch?v=8Wqgr7Ry3dk', 480, 'beginner', 'es', ARRAY['Prompts Avanzados','Cadena de Pensamiento','Optimización'], 'ai-foundations', 'ChatGPT', 10),
('77d2abb2-a86d-40ec-bede-1b13c658dec9', 'Ingeniería de Prompts para ChatGPT', 'Ingeniería de Prompts para ChatGPT', 'Prompt refinement for content, code, and images.', 'Refinamiento de prompts para contenido, código e imágenes.', 'MyGreatLearning', 'https://www.mygreatlearning.com/academy/learn-for-free/courses/ingenieria-de-prompts-para-chatgpt', 240, 'beginner', 'es', ARRAY['Prompts','Contenido','Código con IA'], 'ai-foundations', 'ChatGPT', 11),
('cc31efb3-8329-477e-8e19-8b96ae1e5126', 'Introducción a la IA y Prompt Engineering', 'Introducción a la IA y Prompt Engineering', 'Responsible prompting and daily AI integration for productivity.', 'Prompting responsable e integración diaria de IA para productividad.', 'Founderz / Microsoft', 'https://founderz.com/es/programa/introduccion-a-la-ia-y-prompt-engineering', 300, 'beginner', 'es', ARRAY['IA Responsable','Productividad','Integración Diaria'], 'business', 'Microsoft AI', 3),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'Curso Completo de IA (Español)', 'Curso Completo de IA', 'ChatGPT mastery, prompt creation, automation basics.', 'Dominio de ChatGPT, creación de prompts, fundamentos de automatización.', 'YouTube', 'https://www.youtube.com/watch?v=Phal-sPAunk', 600, 'beginner', 'es', ARRAY['ChatGPT','Automatización','Productividad'], 'automation', 'ChatGPT', 7),
('2fffe876-36e6-47db-b44c-114ec405fc8f', 'IA: Curso Completo y Gratis 2026', 'IA: Curso Completo y Gratis 2026', 'From zero to building GPTs, agents, and vibe coding basics.', 'Desde cero hasta construir GPTs, agentes y fundamentos de vibe coding.', 'YouTube', 'https://www.youtube.com/watch?v=QsqrVQ7aPgQ', 600, 'beginner', 'es', ARRAY['GPTs','Agentes IA','Vibe Coding'], 'automation', 'ChatGPT', 8),
('cc31efb3-8329-477e-8e19-8b96ae1e5126', 'Inteligencia Artificial para Todos (EDteam)', 'Inteligencia Artificial para Todos', 'Basics of generative AI, using ChatGPT/Gemini/Claude, simple automation.', 'Fundamentos de IA generativa, uso de ChatGPT/Gemini/Claude, automatización simple.', 'YouTube (EDteam)', 'https://www.youtube.com/watch?v=DjshEwI6pVk', 1200, 'beginner', 'es', ARRAY['IA Generativa','ChatGPT','Gemini','Claude'], 'business', 'Multiple', 4);
